### ISSUE TITLE
Support puppet configuration via environment.conf

### ISSUE THREAD

**Issue by ljohnston** [jethrocarr/pupistry#12]
Currently, agent.rb specifies puppet configuration (e.g. modulepath) via command-line switches, which override anything that may be specified in environment.conf. Not sure how it would work exactly, but it seems it would be nice if environment.conf config settings were honored.

Thanks,
Lance

**Comment by jethrocarr** [comment]
hi Lance,

This is somewhat intentional since it makes the Puppet run work entirely based on the paths defined in the the Pupistry configuration and ignore the default Puppet configuration files on the OS which often differ from what someone might have in their Pupistry configuration file.

I think the CLI params take preference above all others, but could be possible to make Pupistry read the environments.conf file if it exists and take those values into consideration.

What's the use case for the environments.conf file for you?

regards,
Jethro

**Comment by ljohnston** [comment]
Hey Jethro,

Here's my use case...

I'd like to include some modules in my control repo. Really, all I want is a "role" module and a "profile" module. I tried putting them in a "modules" directory in my control repo, but that directory gets entirely overwritten by pupistry (or r10k, or something). I then tried adding them to a "site" directory in the control repo and setup that directory in environment.conf, and that's when I found that pupistry doesn't use environment.conf.

I realize I could put my roles and profiles in a separate repository, but then I'd have to have two repositories for something that really should be version controlled as a single project. Whenever I add a node to the control repo and update hiera to classify it, I don't want to have to go to _another_ repo to add the actual class. I know I could handle all of the classes and variables via hiera directly, but the roles and profiles provide a nice layer of abstraction between the nodes and the component modules.

This could even be something that gets configured in the pupistry settings file (but environment.conf "feels" like the better option).

Thoughts?

Thanks,
Lance

**Comment by jethrocarr** [comment]
hi Lance,

Yeah so the modules directory won't work due to the r10k workflow, not much can change about that one. Given what you're trying to do, using environment.conf does sound reasonable.

The way you'd need to fix it is to amend `pupistry/lib/pupistry/agent.rb` and write some logic that checks if an `environment.conf` exists in `#{$config['agent']['puppetcode']}/#{environment}` and if so, load and parse it and suck out values to either be merged or replace the ones Pupistry is setting.

If you want to have a go and send me a PR, happy to review and merge if it doesn't break anything for people not using `environment.conf` files.

regards,
Jethro

**Comment by jethrocarr** [comment]
Fixed by pull request 13, thanks @ljohnston
