### ISSUE TITLE
pupistry gem depends on r10k, which prevents installation on ruby 1.8.7 systems

### ISSUE THREAD

**Issue by ryanschwartz** [jethrocarr/pupistry#15]
Depending on r10k for agent machines is not needed - only on build machines.

https://github.com/jethrocarr/pupistry/blob/master/pupistry.gemspec#L42

Dependency hell with r10k downstream dependencies requiring ruby 1.9.X or higher prevents installation on RHEL 6 systems, as system ruby is 1.8.7.

Please consider removing the gemspec dependency on r10k so that agents can run on older rubies - since they don't need r10k to pull/extract/apply artifacts, and make r10k a documentation/installation item.

**Comment by jethrocarr** [comment]
Old versions of Ruby area a bit of a PITA - I've created a branch "legacy" with a build that will run on these older systems.

Happy to merge any PRs that make life easier for old platforms to that branch, but trying to avoid merging it to master since I don't really want to cripple the code base long term by having to support Ruby 1.8.

Note this specifically from legacy branch should solve your issue, but happy to take a PR that does it in a better way.

```
# The latest version of these gems no longer run on Centos 6/Ruby 1.8.7. Hence
# we download specific versions that meet the requirements of Pupistry but also
# still work with CentOS 6. Note that this will get harder in future and at
# some point Pupistry may have to drop CentOS 6 support due to dependencies.
gem install nokogiri --version 1.4.7
gem install r10k --version 1.5.1
```

**Comment by ryanschwartz** [comment]
PITA is putting it nicely. :angel: I didn't think to look at the legacy branch - might be nice to just publish that gem as 'pupistry-legacy' or somesuch. Otherwise we can definitely just build it and stick it somewhere for those systems on 1.8.7.
